---
- name: Configure Jenkins Server
  hosts: jenkins
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install common packages
      ansible.builtin.apt:
        name:
          - git
          - curl
          - unzip
          - python3-pip
          - ca-certificates
          - apt-transport-https
          - software-properties-common
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add azureuser to docker group
      ansible.builtin.user:
        name: azureuser
        groups: docker
        append: yes
